Multiple tweaks
nf-core/reportho pull request #13
Opened 2024-04-30 12:55 UTC by itrujnara

## PR checklist

- [x] Multiple changes in this PR. See commit messages for details.
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If necessary, also make a PR on the nf-core/reportho _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

2024-05-03 12:18 UTC, JoseEspinosa requested changes
Awesome! 🚀 
Only some small questions/suggestions

2024-05-03 12:18 UTC, JoseEspinosa commented on bin/clustal2fasta.py
> +# Written by Igor Trujnara, released under the MIT license
Not sure if this is needed in each single script since the repository already has the MIT license and your attribution could be found in the README

2024-05-03 12:18 UTC, JoseEspinosa commented on bin/yml2csv.py
> +    output_file = sys.argv[3]
Feel free to leave as you want but my OCD make me include this suggestion 😛 
```suggestion
    sample_id   = sys.argv[1]
    input_file  = sys.argv[2]
    output_file = sys.argv[3]
```

2024-05-03 12:18 UTC, JoseEspinosa commented on docs/usage.md
> +BicD2,Q8TD16
Maybe show here that is also to provide a path to a FASTA file?

2024-05-03 12:18 UTC, JoseEspinosa commented on nextflow_schema.json
> +                "skip_inspector": {
I would rename it to `--skip_orthoinspector`

2024-05-03 12:18 UTC, JoseEspinosa commented on subworkflows/local/report.nf
> +        ch_seqhits   = ch_seqinfo.map { [it[0], []] }
Sorry, probably I am missing something but why creating all these empty channels?

2024-05-06 13:04 UTC, itrujnara commented on bin/clustal2fasta.py
> +# Written by Igor Trujnara, released under the MIT license
The checklist mentions this, and I saw some pipelines (e.g. rnaseq) do this, so I put those notes there just in case

2024-05-06 13:14 UTC, itrujnara commented on subworkflows/local/report.nf
> +        ch_seqhits   = ch_seqinfo.map { [it[0], []] }
These are there to ensure that the channels are populated even if the steps that normally generate them are skipped. If this is not done, the report module will not run with downstream analysis turned off, even partially. Is there a more nf-core-idiomatic way to achieve this?

2024-05-06 13:15 UTC, itrujnara commented on nextflow_schema.json
> +                "skip_inspector": {
Renamed, along with other related params. I have not renamed the modules and channels, as they are not user-facing anyway and the names are already long enough. Let me know if this is fine.

2024-05-06 13:16 UTC, JoseEspinosa commented on bin/clustal2fasta.py
> +# Written by Igor Trujnara, released under the MIT license
Fair enough

2024-05-06 13:28 UTC, JoseEspinosa approved these changes
Awesome! 🎸

2024-05-06 13:28 UTC, merged