Added better request error handling
nf-core/reportho pull request #26
Opened 2024-05-13 11:09 UTC by itrujnara

Closes #22 

- added a custom function to utils that throws a custom error if request fails before response
- switched all request scripts to use that function
- added retries to all network processes in config

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] Make sure your code lints (`nf-core lint`). _Except some template files cause old branch_
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`). _It doesn't but I'll still try CI._

2024-05-13 13:01 UTC, JoseEspinosa requested changes
One small suggestion and a question 😄

2024-05-13 13:01 UTC, JoseEspinosa commented on bin/fetch_afdb_structures.py
> +
```suggestion
```

2024-05-13 13:01 UTC, JoseEspinosa commented on conf/modules.config
> +        errorStrategy = 'retry'
Couldn't we catch which error numbers to retry?

2024-05-13 13:05 UTC, itrujnara commented on conf/modules.config
> +        errorStrategy = 'retry'
I don't know, can we? I have to check in the docs

2024-05-13 13:25 UTC, itrujnara commented on conf/modules.config
> +        errorStrategy = 'retry'
Done

2024-05-14 09:23 UTC, JoseEspinosa approved these changes
Awesome job! 
Thanks

2024-05-14 09:24 UTC, merged