Added light mode plots
nf-core/reportho pull request #27
Opened 2024-05-14 10:24 UTC by itrujnara

Closes #14 

- Added light mode plots
- Changed modules and subworkflows accordingly

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] Make sure your code lints (`nf-core lint`). _Something something template, passes on GitHub._
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).

2024-05-14 22:12 UTC, JoseEspinosa requested changes
Some suggestions and questions 😄

2024-05-14 22:12 UTC, JoseEspinosa commented on bin/plot_orthologs.R
> +
```suggestion
customize_theme <- function(font_size, text_color, bg_color) {
  theme(legend.position = "right",
        text = element_text(size = font_size, color = text_color),
        axis.text = element_text(size = font_size, color = text_color),
        panel.grid = element_line(color = text_color),
        plot.background = element_rect(color = bg_color, fill = bg_color),
        panel.background = element_rect(color = bg_color, fill = bg_color))
}

theme_dark <- customize_theme(font_size, text_color_darkmode, bg_color)
theme_light <- customize_theme(font_size, text_color_lightmode, bg_color)
```

2024-05-14 22:12 UTC, JoseEspinosa commented on modules/local/plot_tree.nf
> +    tuple val(meta), path("*_light.png"), emit: plot_light
```suggestion
    tuple val(meta), path("*_light.png"), path("*_dark.png") , emit: plot
```

2024-05-14 22:12 UTC, JoseEspinosa commented on modules/local/plot_orthologs.nf
> +    tuple val(meta), path("*_jaccard_light.png") , emit: jaccard_light
I think this could be simplified 🤔
```suggestion
    tuple val(meta), path("*_supports_light.png"), path("*_supports_dark.png"), emit: supports
    tuple val(meta), path("*_venn_light.png"), path("*_venn_dark.png")        , emit: venn
    tuple val(meta), path("*_jaccard_light.png"), path("*_jaccard_dark.png")  , emit: jaccard
```

2024-05-14 22:12 UTC, JoseEspinosa commented on subworkflows/local/get_orthologs.nf
> +        ch_jaccardplot  = PLOT_ORTHOLOGS.out.jaccard_dark.join(PLOT_ORTHOLOGS.out.jaccard_light, by: 0)
```suggestion
        ch_supportsplot = PLOT_ORTHOLOGS.out.supports
        ch_vennplot     = PLOT_ORTHOLOGS.out.venn
        ch_jaccardplot  = PLOT_ORTHOLOGS.out.jaccard
```

2024-05-14 22:12 UTC, JoseEspinosa commented on subworkflows/local/make_trees.nf
> +            ch_mlplot = PLOT_IQTREE.out.plot_dark.join(PLOT_IQTREE.out.plot_light, by: 0)
```suggestion
            ch_mlplot = PLOT_IQTREE.out.plot
```

2024-05-14 22:12 UTC, JoseEspinosa commented on subworkflows/local/make_trees.nf
> +            ch_meplot = PLOT_FASTME.out.plot_dark.join(PLOT_FASTME.out.plot_light, by: 0)
```suggestion
            ch_meplot = PLOT_FASTME.out.plot
```

2024-05-14 22:12 UTC, JoseEspinosa commented on workflows/reportho.nf
> +        ch_iqtree = MAKE_TREES.out.mlplot.map { [it[0], it[1]] }
Maybe I am not understanding, but here you want to pass both the dark and light plots, right? if yes, won't be `it[1]` and `it[2]`?

2024-05-15 08:34 UTC, itrujnara commented on workflows/reportho.nf
> +        ch_iqtree = MAKE_TREES.out.mlplot.map { [it[0], it[1]] }
This is the part related to the report, so only the dark mode plots are necessary, as the report is in dark mode. The meta is passed because the subworkflow uses it to organize the files.

2024-05-15 12:53 UTC, JoseEspinosa approved these changes
LGTM! 🚀

2024-05-15 12:54 UTC, merged