Added offline run flag and profile
nf-core/reportho pull request #29
Opened 2024-05-15 13:58 UTC by itrujnara

Closes #28 

- added `offline_run` option
- added `offline` profile

Note: the options only affect the ortholog fetching, downstream still requires network. FASTA input is not available for offline runs for now.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).

2024-05-21 10:04 UTC, JoseEspinosa requested changes
I added some suggestions. Not sure if we should also check for any DBs that can not be run offline when the `--offline` parameter is set to also trough a warning

2024-05-21 10:04 UTC, JoseEspinosa commented on conf/offline.config
> +    local_databases = true
Don't you need also to provide here the paths to the local DBs?

2024-05-21 10:04 UTC, JoseEspinosa commented on subworkflows/local/get_orthologs.nf
> +    if (fasta_input && params.offline_run) {
Do we want to through a warning  here instead making clear that using `fasta` could have an impact on the rate limit if too many files are provided?

2024-05-21 10:04 UTC, JoseEspinosa commented on subworkflows/local/get_orthologs.nf
> +    if(params.use_all && params.offline_run) {
Probably, this should go to `subworkflows/local/utils_nfcore_reportho_pipeline/main.nf
```suggestion
        warning("Both '--use_all' and '--offline_run' parameters have been specified!\nThose databases that can't be run offline will be run online.")
```

2024-05-21 10:10 UTC, itrujnara commented on conf/offline.config
> +    local_databases = true
I don't think I can. I have no prior knowledge of the file structure on the user's machine.

2024-05-22 10:21 UTC, JoseEspinosa commented on conf/offline.config
> +    local_databases = true
As discussed on slack I was referring of creating a small version of the databases for running a test using the `offline` mode

2024-05-22 10:22 UTC, itrujnara commented on conf/offline.config
> +    local_databases = true
Done now, see `test_offline.config`

2024-05-23 10:04 UTC, JoseEspinosa approved these changes
Thanks! LGTM 🚀

2024-05-23 10:05 UTC, merged