Bug fixes
nf-core/reportho pull request #46
Opened 2024-05-29 11:25 UTC by itrujnara

Fixed a few errors caused by nonexistent files
Fixed isoform handling in OMA fetch
Improved large script readability
Added execute permissions to report run script

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).

2024-05-30 17:55 UTC, JoseEspinosa requested changes
Just some small comments but very nice! 😄 
Maybe we could add to `safe_get` to `requests.get` a timeout, this way even if the problem is in the user site as with the new CRG cluster it won't stay idle for ever, something such as:
`return requests.get(url, timeout = 300)`

2024-05-30 17:55 UTC, JoseEspinosa commented on bin/fetch_oma_group.py
```suggestion
```

2024-05-30 17:55 UTC, JoseEspinosa commented on bin/fetch_panther_group.py
> +        pass # yes, I mean this, we just want to return an empty file if nothing is found
😆 Nice comment! Maybe we could add a warning here? Something as "id not found"?

2024-05-30 17:55 UTC, JoseEspinosa commented on modules/local/fetch_eggnog_group_local.nf
> +        Python: \$(python --version | cut -d' ' -f2)
Not a strong opinion but in nf-core modules normally done as below, for consistency we could use the same:
```suggestion
        python: \$(python --version | sed 's/Python //g')
```

2024-05-30 17:55 UTC, JoseEspinosa commented on modules/local/fetch_oma_group_local.nf
> +    uniprot2oma_local.py $uniprot_idmap $uniprot_id > oma_id.txt || test -f oma_id.txt
😍

2024-05-30 17:55 UTC, JoseEspinosa commented on modules/local/fetch_oma_group_local.nf
> +        Python: \$(python --version | cut -d' ' -f2)
Same here:
```suggestion
        python: \$(python --version | sed 's/Python //g')
```

2024-05-30 17:55 UTC, JoseEspinosa commented on modules/local/fetch_oma_group_local.nf
> +        Python: \$(python --version | cut -d' ' -f2)
again 😄 
```suggestion
        python: \$(python --version | sed 's/Python //g')
```

2024-05-30 17:55 UTC, JoseEspinosa commented on modules/local/fetch_panther_group_local.nf
> +        Python: \$(python --version | cut -d' ' -f2)
```suggestion
        python: \$(python --version | sed 's/Python //g')
```

2024-05-30 17:55 UTC, JoseEspinosa commented on modules/local/fetch_panther_group_local.nf
> +        Python: \$(python --version | cut -d' ' -f2)
```suggestion
        python: \$(python --version | sed 's/Python //g')
```

2024-05-31 12:04 UTC, itrujnara commented on bin/fetch_panther_group.py
> +        pass # yes, I mean this, we just want to return an empty file if nothing is found
Might be tricky, as the module captures stderr from this script to get the database version

2024-05-31 15:32 UTC, JoseEspinosa approved these changes
Awesome! thanks! 🚀

2024-05-31 16:30 UTC, merged