Patch release 1.0.1
nf-core/reportho pull request #57
Opened 2024-06-14 10:36 UTC by itrujnara

Fixed bugs that caused crashes, removed some unnecessary file publishing

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [x] If you've fixed a bug or added code that should be tested, add tests!
- [x] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/reportho/tree/master/.github/CONTRIBUTING.md)
- [x] If necessary, also make a PR on the nf-core/reportho _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

2024-06-14 10:48 UTC, JoseEspinosa approved these changes
LGTM, just a small tyop corrected (c/p error likely)

2024-06-14 10:48 UTC, JoseEspinosa commented on CHANGELOG.md
> +## [v1.0.1](https://github.com/nf-core/reportho/releases/tag/1.0.1) [2024-06-11]
Remember to update if not released today
```suggestion
## [v1.0.1](https://github.com/nf-core/reportho/releases/tag/1.0.1) [2024-06-14]
```

2024-06-14 11:36 UTC, mashehu commented on CHANGELOG.md
> +- Fixed minor bugs that caused compilation errors in the structural alignment section
any way to catch these kind of things with different parameter matrices in the CI tests?

2024-06-14 12:31 UTC, JoseEspinosa requested changes
Also, seems that test are failing, please fix the issue before merging

2024-06-14 14:16 UTC, itrujnara commented on CHANGELOG.md
> +- Fixed minor bugs that caused compilation errors in the structural alignment section
Definitely, I can create a test for that. However, that means quite a lot of extra computation at each CI run. What do you say?

2024-06-18 09:52 UTC, itrujnara commented on CHANGELOG.md
> +- Fixed minor bugs that caused compilation errors in the structural alignment section
@mashehu

2024-07-15 11:30 UTC, JoseEspinosa commented on CHANGELOG.md
> +- Fixed minor bugs that caused compilation errors in the structural alignment section
Would be nice if we could move this forward to make available the output of the pipeline into the nf-core web

2024-07-15 11:54 UTC, mashehu approved these changes

2024-07-15 11:54 UTC, mashehu commented on CHANGELOG.md
> +- Fixed minor bugs that caused compilation errors in the structural alignment section
okay for me if the tests are actually too computationally expensive

2024-07-18 12:42 UTC, JoseEspinosa approved these changes
The full test have successfully run so I think it is time to release the patch 🎉

2024-07-18 12:44 UTC, merged