Back to dev again
nf-core/reportho pull request #59
Opened 2024-10-07 16:36 UTC by itrujnara

## PR checklist

Merge of patch content from master and version bump to 1.1dev

- [x] This comment contains a description of changes (with reason).
- [x] Make sure your code lints (`nf-core lint`).
- [x] `CHANGELOG.md` is updated.

2024-10-07 17:39 UTC, mashehu approved these changes

2024-10-07 17:40 UTC, mashehu requested changes

2024-10-07 17:40 UTC, mashehu commented on CHANGELOG.md
> +## [v1.1]
```suggestion
## [v1.1.0]
```
Please use full semver

2024-10-07 19:33 UTC, JoseEspinosa approved these changes
LGTM!

2024-10-08 09:35 UTC, mashehu reviewed
I am a bit confused is to a version bump from a new release back to dev or from a prep for a new release?

2024-10-08 09:44 UTC, itrujnara commented
> I am a bit confused is to a version bump from a new release back to dev or from a prep for a new release?

We had a patch because of Megatest issues, then when we merged the changes back into dev the version number 1.0.1 got merged as well and we need it to be 1.1dev here for the time being

2024-10-08 09:47 UTC, mashehu approved these changes

2024-10-08 09:47 UTC, mashehu commented on CHANGELOG.md
> +## [v1.1.0]
```suggestion
## [v1.1.0dev]
```
like this then?

2024-10-08 09:47 UTC, mashehu commented on CHANGELOG.md
> +## [v1.1.0]
(better to actually use `nf-core bump-version 1.1.0dev` to also edit the mutliqc config correctly)

2024-10-08 17:15 UTC, itrujnara commented
Template merge hell has started here, can someone more experienced help?

2024-10-09 14:12 UTC, itrujnara commented
Force-merging with failing tests – the errors are due to unmerged 3.0 template

2024-10-09 14:12 UTC, merged