Add subworkflow to get sequences
nf-core/reportho pull request #67
Opened 2024-11-04 14:01 UTC by itrujnara

Add a subworkflow that obtains ortholog sequences from databases. It's much more robust than the current module.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests! _Not yet, we'll get there_
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).

2024-11-04 14:06 UTC, itrujnara commented
@nf-core-bot fix linting

2024-11-04 14:17 UTC, JoseEspinosa requested changes
Very nice job! 🚀  
Some minor comments from my side

2024-11-04 14:17 UTC, JoseEspinosa commented on subworkflows/local/get_sequences.nf
> +    ch_misses_grouped = ch_misses.groupTuple()
```suggestion
    ch_fasta_grouped  = ch_fasta.groupTuple()
    ch_hits_grouped   = ch_hits.groupTuple()
    ch_misses_grouped = ch_misses.groupTuple()
```

2024-11-04 14:17 UTC, JoseEspinosa commented on subworkflows/local/get_sequences.nf
> +    ch_idfiles = SPLIT_ID_FORMAT.out.ids_split.transpose().branch {
For consistency with the rest of the naming I will use `ch_id_files` but it is just a suggestion, if you prefer it this way keep it
```suggestion
    ch_id_files = SPLIT_ID_FORMAT.out.ids_split.transpose().branch {
```

2024-11-04 14:17 UTC, JoseEspinosa commented on subworkflows/local/get_sequences.nf
> +        ch_idfiles.ensembl.join(ch_query_fasta),
```suggestion
        ch_id_files.ensembl.join(ch_query_fasta),
```

2024-11-04 14:17 UTC, JoseEspinosa commented on conf/modules.config
> -    withName: 'FETCH_SEQUENCES_ONLINE' {
This is just gone and not replaced by `FETCH_OMA_SEQUENCES` ?

2024-11-04 14:17 UTC, JoseEspinosa commented on modules/local/convert_fasta.nf
> +    // THINGS ARE WRONG HERE, FIXME WHEN SEQERA CONTAINTAINERS START TO COOPERATE
What does this comment mean?

2024-11-04 14:17 UTC, JoseEspinosa commented on modules/local/convert_fasta.nf
> +    conda "conda-forge::python=3.12.0 conda-forge::biopython=1.84.0 conda-forge::requests=2.32.3"
At some point, for sure not for this PR, maybe think of adopting the structure of the nf-core modules, with an `envinroment.yml` and maybe tests?

2024-11-04 14:17 UTC, JoseEspinosa commented on modules/local/fetch_refseq_sequences.nf
> +    path "versions.yml"                          , emit: versions
```suggestion
    tuple val(meta), path("*_refseq_seq_misses.txt"), emit: misses
    path "versions.yml"                             , emit: versions
```

2024-11-04 16:16 UTC, itrujnara commented on conf/modules.config
> -    withName: 'FETCH_SEQUENCES_ONLINE' {
It is indeed replaced

2024-11-07 14:41 UTC, itrujnara commented on modules/local/convert_fasta.nf
> +    conda "conda-forge::python=3.12.0 conda-forge::biopython=1.84.0 conda-forge::requests=2.32.3"
Perhaps

2024-11-08 13:04 UTC, JoseEspinosa approved these changes
Thanks! LGTM 🚀

2024-11-08 13:05 UTC, merged